In [1]:
import numpy as  np      

In [4]:
# create an array of zeros
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [8]:
# integers fron 10,50
np.arange(10,50+1)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [9]:
# integers fron 10,50 even intergers
np.arange(10,50+1,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [15]:
arr=np.arange(0,9)
print(arr)
arr.reshape((3,3))


[0 1 2 3 4 5 6 7 8]


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [21]:
# identity matrix -- not take tuple because identity matrix is of nxn matrix
np.eye(5,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [ ]:
np.random.rand()



array([0.21703206])

In [ ]:
np.random.rand(1)

In [35]:
np.random.rand(3,4)

array([[0.94335471, 0.91667171, 0.31546113, 0.65260419],
       [0.32766406, 0.30624512, 0.05225469, 0.28610044],
       [0.09028947, 0.65683801, 0.8243779 , 0.87517432]])

In [ ]:
# 25 random values from standard normal distribution
np.random.randn(25)

array([ 0.95537683,  0.4630359 ,  0.11952731, -1.6672894 , -0.87898787,
        0.63594929, -1.23085947, -0.78983106, -0.40097812, -0.44790681,
       -0.74864231, -0.14057431, -0.73130421, -0.98210837,  1.07948743,
        0.43003194,  1.11838617, -0.89586723, -0.19652959,  1.24186876,
       -0.22490972,  0.08790168, -1.13468392, -1.06506961, -1.56088766])

In [47]:
matrix=np.arange(0.01,1.01,0.01)
matrix.reshape(20,5)
matrix.reshape(10,10)



array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])